### ISSUE TITLE
The quest The Nether has a repeteable dependant

### ISSUE THREAD

**Issue by AlexCode10010** [TacocaTYT/Hexblock#2]
I've looked into the quest and it one of its dependants is a repeteable quest (Pyromancy). Since that quest's reward is necessary to reach the nether the quest will reset, requiring you to complete this quest twice just to obtain The Nether quest.

**Comment by TacocaTYT** [comment]
ah thank you for pointing this out, ill look into some fixes for it asap

**Comment by TacocaTYT** [comment]
fixed in latest
